---
- name: update hosts file
  become: true
  become_user: root
  lineinfile: dest=/etc/hosts
              regexp="^127\.0\.0\.1 localhost(?! {{ private_dns_name }})?"
              line="127.0.0.1 localhost {{ private_dns_name }} {{ private_dns_name|regex_replace('\..*', '') }}"
              state="present"

- name: set hostname to private_dns_name
  become: true
  become_user: root
  hostname:
    name: "{{ private_dns_name }}"

- name: update and upgrade apt packages
  become: true
  become_user: root
  apt: >
    upgrade=dist
    update_cache=yes
    cache_valid_time=3600
  register: apt_upgrade

- name: restart machine
  become: true
  become_user: root
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  ignore_errors: true
  when: apt_upgrade.changed

- name: waiting for server to come back
  local_action: wait_for host={{ ansible_eth0.ipv4.address }} state=started port=22 delay=15 timeout=300
  become: false
  when: apt_upgrade.changed
